### ISSUE TITLE
v1.5.0 is actually 1.4.0 and tries to download an update for AppImage

### ISSUE THREAD

**Issue by sreich** [la-jarre-a-son/midi-jar#22]
## Expected Behavior

That installing the 1.5.0 appimage says 1.5.0 on startup

## Current Behavior
It says 1.4.0 on the startup and then says it will download it. But I don't think the self updating works properly for AppImages (linux) anyways. Unless the auto updater isn't pointed correctly to the latest version
## Your Environment

- MIDI Jar version:1.5.0
- Operating System:Archlinux
- Hardware Devices:

**Comment by ArTiSTiX** [comment]
Hello @sreich !

I might have to disable the autoupdater, since the app is not signed, is suspect this is prevented. Or maybe i could have time and money to buy certificates so that this is not an issue.

I'm keeping this is mind for next release.

**Comment by ArTiSTiX** [comment]
@sreich have you tried installing directly from the release on github ?
I want to be sure this is not an issue with the current appimage that has been built, i did not test it.
I will try to make a signed version of MIDI Jar as soon as possible so that auto updater is working (and installing MIDI Jar not a pain that could discourage someone to try it).

**Comment by sreich** [comment]
Yep when I filed the issue I uninstalled it and downloaded 1.5.0 straight but launching it was showing 1.4.0 on the update notes. Not very familiar with appimage so I can't guarantee anything, I just know that it's the "worse" option versus flatpak, which has auto updating built in

But unfortunately as it stands right now I can't try 1.5.0, which is a shame because I've been excited about those chord improvements I've been hearing about!

**Comment by ArTiSTiX** [comment]
Oh, ok, i'm not familiar with the AppImage either (nor the Linux environment), i will have a look into this.
Concerning flatpak, what do you mean by "auto updating built in" ?
Are we talking about flathub, or manually installed flatpak apps ?

Because i was also considering your other issue about flatpak, which can be built somehow with electron-builder (so a one line change to midi jar i suppose), but since i have no idea of how it works, i did not added flatpak as a build destination.
But publishing to flathub is on another level, and might not be easy with electon-builder.

**Comment by sreich** [comment]
Yup, I was referring to flathub. I'm not familiar with that process either, but when I took a glance at creating a flatpak it didn't seem difficult

https://www.electron.build/configuration/flatpak.html

Looks like there are still plans, following the link it looks like they assigned developers to the task.

But, either way, even without flathub, flatpak would be a better choice overall I think. The appimage experience in my opinion isn't as good from a user perspective

I do wonder how internal auto updates behave with that sort of app package, but not something I've needed to work with so haven't researched any of that

**Comment by ArTiSTiX** [comment]
Hello @sreich !

I tested on Ubuntu the AppImage for v1.5.0, and without difficulty it was working (showing 1.5.0). I have no idea why your system would keep 1.4.0 living (you must ensure it is closed though, since only 1 instance of midi-jar can run).

But i disabled the auto-update (it was working on Windows :p but i'm not fond of softwares not asking before updating) so there should be no confusion about it being a manual action.

Please close this ticket if you succeed to run 1.5.1

**Comment by sreich** [comment]
Okay thank you! Yeah perhaps it was something stale on my system

Either way, I'm not running the latest thanks to the new flatpak support, and that integrates much better with kde\archlinux

Closing
