### ISSUE TITLE
Recognize invertions and display more common chords first

### ISSUE THREAD

**Issue by gotthehot** [la-jarre-a-son/midi-jar#24]
Issue has been [forwarded](https://github.com/tonaljs/tonal/issues/242#issuecomment-1816164197) to author of tonal library, but may be useful here for tuning display algorithm when several variants available.

## Expected Behavior

E-A-C triad is expected to be displayed as Am/E

## Current Behavior

E-A-C chord recognizing as C6/E without alternatives

![am-inversion](https://github.com/la-jarre-a-son/midi-jar/assets/17710120/378e792e-5c37-450d-828f-bd78b0ed4457)

Yes, it could be C6 with omitted V, but primary display should be basic minor triad.

Soon I found than midi-jar do not recognize inversions (as in Am/E case) or treat them as very uncommon chords for main display. For example when playing simple D major chord inversion from A (**A-D-F#**) midi-jar displays as main choice a very uncommon **Gb6addb6/A** chord and then small display of **DM/A** that is definitely more relevant in most cases.

![d-inversion](https://github.com/la-jarre-a-son/midi-jar/assets/17710120/f629245f-7323-43ba-af3e-2f36e5338572)

## Steps to Reproduce

1. Play almost any triad inversion

## Suggested Solution (if any)

Tune algorithm of chords recognition to recognize inversions and display most relevant (simplest, most common) variants first.

## Your Environment

- MIDI Jar version: 1.5.0 (2023-11-07)
- Operating System: Windows 10 64-bit
- Hardware Devices: USB MIDI Keyboard

**Comment by ArTiSTiX** [comment]
@gotthehot Thanks for the suggestion.

In the current state, MIDI Jar (which uses https://github.com/tonaljs/tonal for all the music stuff) sorts chords this way:
* Exact match with same root note (score 1)
* Chord with omission (score 0.75) - _if enabled_
* Chord inversion (score 0.5)
* Chord inversion with omission (score 0.375) - if _enabled_

The number of omissions is not taken into account. In case of equality, the chords follow the order in dictionary.

Maybe inverting priority between omission and inversion could solve the issue (or adding a settings to choose to), like 0.5 coefficient for omission, and 0.75 for inversion could do it, but it could also make some chords be recognized as inversions where as they're not.

I could also add another variable to sort chords, but this is empirical: for the chord quiz module, i created a "complexity" score, which scores higher depending on the intervals (https://github.com/la-jarre-a-son/midi-jar/blob/main/src/renderer/hooks/useQuiz/utils.ts#L57-L83).
If inverting the omission/inversion score is not sufficient, this could be a way to sort this out.

I'm gonna add this setting along with the other ticket in a few day so that you can test it.

**Comment by gotthehot** [comment]
> NOTE: on my end, E-A-C correctly results in a Am/E (but as the second detected alternative if omissions are allowed).

Sorry, that's my fault. Occasionally turned "display alternative chords" off while experimenting with detection.

On topic. In case of E-A-C both Am and C6 are inversions, so C6 selected as primary due to omission. Hmmm... For me it's lack of logic. For me it's strange to see relatively rare C6 while playing simple Am. Imagine face of beginner learning triad inversions :) So I vote for triad inversion to be of highest priority when selecting variants. Configurable - may be, but default - at least.

**Comment by gotthehot** [comment]
Author of tonal just [answered](https://github.com/tonaljs/tonal/issues/242#issuecomment-1817961409) my report: tonal always returns inversions after main chord, so the matter is priority in midi-jar, not tonal.

**Comment by ArTiSTiX** [comment]
@gotthehot yes this is a bug in midi-jar, i inverted a condition without notice. I'll be working on it to patch 1.5.0 with other changes you mentionned.

Note that i changed the tonal dictionary and the dectection code to allow omission, and midi-jar is my way to test it before submitting change to tonal.

**Comment by ArTiSTiX** [comment]
Oops, sorry @gotthehot I unintentionally closed  this ticket.

The v1.5.1 update should fix the issue of inverted chords with omissions being displayed before chords without omissions.

Note that chords with only omissions will still be displayed before inversions.

If you find any issue with it, you can create a new ticket, and if you find new strange behaviour (or mistakes) i would be happy to fix it too :)
