### ISSUE TITLE
Impossible to clone and run this repo because of private npm repositories

### ISSUE THREAD

**Issue by evgeniyp** [la-jarre-a-son/midi-jar#35]
I tried to clone the repo, but the `npm install` command says there are npm dependencies that I am not authorized to download. It would be nice to use public ones only.

**Comment by ArTiSTiX** [comment]
Hello @evgeniyp 

MIDI Jar uses npm packages hosted by github (it's not really private, it's simply not hosted on the public npm registry).
You need to be authenticated to the github npm registry to install those packages.

This is very useful in my case because:
* I forked some packages that need to be built and published somewhere, but not relevant to be published on a npm registry
* The ui library is not open source at this time and is not under a free license like MIT.
* This is my way to keep control over my free software.

Here is the Github guide to authenticate npm to github: https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-npm-registry

**Comment by evgeniyp** [comment]
Thank you very much for the detailed explanation!
