### ISSUE TITLE
Add easier key selection

### ISSUE THREAD

**Issue by sreich** [la-jarre-a-son/midi-jar#4]
Switching keys is inconvenient. I only use the mouse when i'm at my piano

I was thinking..a way to improve upon this, perhaps a dropdown embedded on the chord display that shows and lets you edit the current key

But I think what would be even better is, adding the circle of 5ths on the chord display, then clicking it will switch to that key. Also be very great for teaching/showing/learning

**Comment by ArTiSTiX** [comment]
That's a good idea, i didn't think switching key would be often used, but i can clearly come to something more convenient.

I'm planning to (optionally) highlight the scale on the piano, and being able to play it directly with mouse or touch, so using it for switching key will not be the solution i choose.

Though, I can definitely make the label over the signature clickable to open a circle of fifth, this would be fun to develop :)
+ i always have a hard time figuring out the relative minor scale, and its key, so that would be a solution.

I don't really like dropdowns, and they are not implemented, but i soon will have to anyway.

**Comment by sreich** [comment]
Yeah me too, it can help you think of , the relative minor is 3 half steps below the root of your major. The reverse for going the other way

I agree with your opinion on dropdowns. I think when you make the circle of fifths it would be best to just make each key clickable there. Then no need for drop downs or any other input for it

**Comment by ArTiSTiX** [comment]
@sreich I added a Circle of Fifths module, with a lot (too much) of customizations, you can add sections for any chords (except augmented chords that rarely fits any common scale).

I chose to make it a chord vizualizer, with a few sections by default, but you should be able to make it simpler, and interact on notes instead of chords.

And this module let you change the key by clicking on any sector, so it also serve the initial purpose.
Mine was to be able to choose a key for a minor scale without having to calculate the relative major of the key i want to play in... now i can even see where i can go when playing 7th dominant chords (with the dominant chords section, dominant substitutions is a magical tool to create chord progressions).

LMKWYT about my choices, and thanks for the suggestion, i really liked working on it.

**Comment by sreich** [comment]
sweet! that seems nice, i'm looking forward to using it, thanks for implementing that and your repsonsiveness.

Though have to wait until it doesn't give ALSA issues
